# Generated by Django 2.2.11 on 2020-03-24 02:50
import django.db.models.deletion
import django_fsm
import phonenumber_field.modelfields
import taggit.managers
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorizer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("homepage_url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STATE", "State"),
                            ("GLOBAL", "Global"),
                            ("NATIONAL", "National"),
                            ("LOCAL", "Local"),
                        ],
                        default=("STATE", "State"),
                        max_length=32,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("authoritative_url", models.URLField(blank=True, null=True)),
                (
                    "impact_area",
                    models.CharField(
                        choices=[
                            ("STATE", "State"),
                            ("GLOBAL", "Global"),
                            ("NATIONAL", "National"),
                            ("LOCAL", "Local"),
                        ],
                        default=("STATE", "State"),
                        max_length=32,
                    ),
                ),
                ("status", django_fsm.FSMField(default="new", max_length=50)),
                ("published_on", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "authoritative_publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.Publisher",
                    ),
                ),
                (
                    "authorizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.Authorizer",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={"ordering": ["created_on"],},
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Item"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.Publisher",
                    ),
                ),
            ],
        ),
    ]
