# Generated by Django 3.0.4 on 2020-03-23 23:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authorizor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("press_release_url", models.URLField(blank=True, null=True)),
                (
                    "impact_area",
                    models.CharField(
                        choices=[
                            ("STATE", "State"),
                            ("GLOBAL", "Global"),
                            ("NATIONAL", "National"),
                            ("LOCAL", "Local"),
                        ],
                        default=("STATE", "State"),
                        max_length=32,
                    ),
                ),
                ("published_on", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "authorizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.Authorizor",
                    ),
                ),
            ],
        ),
    ]
