# Generated by Django 2.2.11 on 2020-03-24 00:18
import django_fsm
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200323_1950"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item", options={"ordering": ["created_on"]},
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=django_fsm.FSMField(default="new", max_length=50),
        ),
        migrations.AddField(
            model_name="publisher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
