# Generated by Django 2.2.11 on 2020-03-24 00:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200323_2018"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizor",
            name="name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
