# Generated by Django 2.2.11 on 2020-03-24 01:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_authorizor_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="press_release_publisher",
            new_name="authoritative_publisher",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="press_release_url",
            new_name="authoritative_url",
        ),
    ]
