# Generated by Django 2.2.11 on 2020-03-24 13:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200324_0911"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="tags", field=models.ManyToManyField(to="api.Tag"),
        ),
    ]
