# Generated by Django 2.2.11 on 2020-03-24 13:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_event_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="impact_area",),
        migrations.AddField(
            model_name="event",
            name="scope",
            field=models.CharField(
                choices=[
                    ("GLOBAL", "Global"),
                    ("US", "United States"),
                    ("OHIO", "Ohio"),
                    ("COLUMBUS", "Columbus"),
                    ("CLEVELAND", "Cleveland"),
                    ("CINCINNATI", "Cincinnati"),
                    ("DAYTON", "Dayton"),
                ],
                default=("GLOBAL", "Global"),
                max_length=32,
            ),
        ),
    ]
