# Generated by Django 2.2.11 on 2020-03-24 13:38
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20200324_0921"),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["created_on"],},
        ),
        migrations.CreateModel(
            name="Breakout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cases", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("as_of", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.County"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Authorizer"
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
                "unique_together": {("county", "as_of")},
            },
        ),
    ]
