# Generated by Django 2.2.11 on 2020-03-24 13:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_breakout_county"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breakout", options={"ordering": ["as_of", "county__name"]},
        ),
        migrations.AlterModelOptions(
            name="county",
            options={"ordering": ["name"], "verbose_name_plural": "counties"},
        ),
    ]
