# Generated by Django 2.2.11 on 2020-03-24 14:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20200324_0948"),
    ]

    operations = [
        migrations.RemoveField(model_name="breakout", name="source",),
        migrations.AlterField(
            model_name="county", name="name", field=models.TextField(unique=True),
        ),
    ]
