# Generated by Django 2.2.11 on 2020-03-24 14:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20200324_1040"),
    ]

    operations = [
        migrations.RenameModel(old_name="Breakout", new_name="Case",),
    ]
