# Generated by Django 2.2.11 on 2020-03-24 14:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200324_1044"),
    ]

    operations = [
        migrations.RenameField(model_name="case", old_name="cases", new_name="total",),
    ]
