# Generated by Django 2.2.11 on 2020-03-24 15:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_case_recovered"),
    ]

    operations = [
        migrations.AlterModelOptions(name="tag", options={"ordering": ["name"]},),
    ]
