# Generated by Django 2.2.11 on 2020-03-24 21:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20200324_1121"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("Other", "Other"),
                    ("Education/Childcare", "Education/Childcare"),
                    ("Recreation/Events", "Recreation/Events"),
                    ("Food/Dining", "Food/Dining"),
                    ("Medical", "Medical"),
                    ("Legal", "Legal"),
                    ("Employment/Business", "Employment/Business"),
                    ("Political", "Political"),
                ],
                default=("Other", "Other"),
                max_length=32,
            ),
        ),
    ]
