# Generated by Django 2.2.11 on 2020-03-24 21:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="title", field=models.TextField(),
        ),
    ]
