# Generated by Django 2.2.11 on 2020-03-24 22:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20200324_1748"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="category",),
    ]
