# Generated by Django 2.2.11 on 2020-03-24 22:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_event_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="slug",),
    ]
