# Generated by Django 2.2.11 on 2020-03-24 22:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scope",
            field=models.CharField(
                choices=[
                    ("Global", "Global"),
                    ("United States", "United States"),
                    ("Ohio", "Ohio"),
                    ("Columbus", "Columbus"),
                    ("Cleveland", "Cleveland"),
                    ("Cincinnati", "Cincinnati"),
                    ("Dayton", "Dayton"),
                ],
                default=("Global", "Global"),
                max_length=32,
            ),
        ),
    ]
