# Generated by Django 2.2.11 on 2020-03-25 01:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20200324_1810"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event", options={"ordering": ["-created_on"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="scope",
            field=models.CharField(
                choices=[
                    ("Global", "Global"),
                    ("National", "National"),
                    ("State", "State"),
                    ("Columbus", "Columbus"),
                    ("Cleveland", "Cleveland"),
                    ("Cincinnati", "Cincinnati"),
                    ("Dayton", "Dayton"),
                ],
                default=("Global", "Global"),
                max_length=32,
            ),
        ),
    ]
