# Generated by Django 2.2.11 on 2020-03-26 16:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_auto_20200324_2101"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("www", "www"),
                    ("twitter", "twitter"),
                    ("youtube", "youtube"),
                    ("vimeo", "vimeo"),
                    ("image", "image"),
                    ("pdf", "pdf"),
                ],
                default=("www", "www"),
                max_length=20,
            ),
        ),
    ]
