# Generated by Django 2.2.11 on 2020-03-26 16:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_event_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("www", "www"),
                    ("twitter", "twitter"),
                    ("youtube", "youtube"),
                    ("vimeo", "vimeo"),
                    ("image", "image"),
                    ("pdf", "pdf"),
                ],
                default="www",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="scope",
            field=models.CharField(
                choices=[
                    ("Global", "Global"),
                    ("National", "National"),
                    ("State", "State"),
                    ("Columbus", "Columbus"),
                    ("Cleveland", "Cleveland"),
                    ("Cincinnati", "Cincinnati"),
                    ("Dayton", "Dayton"),
                ],
                default="Global",
                max_length=32,
            ),
        ),
    ]
