# Generated by Django 2.2.11 on 2020-04-02 18:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_auto_20200326_1254"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="authoritative_publisher",),
    ]
