# Generated by Django 2.2.11 on 2020-04-10 20:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_event_authoritative_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article", options={"ordering": ["-created_on", "id"]},
        ),
        migrations.AlterModelOptions(
            name="authorizer", options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="case", options={"ordering": ["-as_of", "county__name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="county",
            options={"ordering": ["name", "id"], "verbose_name_plural": "counties"},
        ),
        migrations.AlterModelOptions(
            name="event", options={"ordering": ["-published_on", "id"]},
        ),
        migrations.AlterModelOptions(
            name="publisher", options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(name="tag", options={"ordering": ["name", "id"]},),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(related_name="events", to="api.Tag"),
        ),
    ]
