# Generated by Django 2.2.11 on 2020-04-10 20:11
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_auto_20200410_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="api.Publisher",
            ),
        ),
    ]
