# Generated by Django 2.2.11 on 2020-04-10 21:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_auto_20200410_1611"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("file", models.FileField(upload_to="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["created_on", "id"],},
        ),
    ]
